SHELL := /bin/bash
# Defines rules to generate [filename].pdf, and [filename].tex
# Output files are generated by inputting [filename].md (markdown)
# into pandoc

%.pdf: %.md
%.tex: %.md
	pandoc -F mermaid-filter "$<" -o "$@"
	rm mermaid-filter.err

# This defines the command `make wslSetup`
#
# This command should when run in WSL (Windows Subsystem for Linux)
# - install pandoc
# - Install NPM,
# - use NPM to install mermaid support for pandoc
wslSetup:
	sudo apt install pandoc npm
	sudo npm install --global mermaid-filter

macSetup:
	sudo brew install pandoc npm
	sudo npm install --global mermaid-filter

# These last two definitions are for the commands `make pdf` and `make tex`
#
# running `make pdf` (for example) will find all .md files, and then
# ask `make` to generate corresponding .pdf files.
pdf: $(shell \
	find -name "*.md" -print0 \
	| xargs -0 ls -b \
	| sed -e 's/.md/.pdf/' \
	| tr '\n' ' ' \
)

tex: $(shell \
	find -name "*.md" -print0 \
	| xargs -0 ls -b \
	| sed -e 's/.md/.tex/' \
	| tr '\n' ' ' \
)
